import { Button } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js</a> and <a href="https://about.gitlab.com/">Gitlab</a> OAuth Integration
        </h1>
        <Link href="/login" passHref>
          <Button variant="contained" size="large" sx={{ m: '1rem' }}>
            Login Here
          </Button>
        </Link>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://tamim-cv.netlify.app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Tamim Jabr
        </a>
      </footer>
    </div>
  )
}

export default Home
